<?php

use PHPUnit\Framework\TestCase;
Use App\Http\Controllers\MyController;

//require __DIR__ . "/../src/MyController.php";


class ArtistSuggestTest extends TestCase{


	/**
	 * @covers App\Http\Controllers\MyController::getArtistListFromJSON()
	**/
	public function testGetArtistFromJSONOnSuccessfulJSONResponse(){

		$myController = new MyController();
		$responseBody = array ( 'message' => array ( 'header' => array ( 'status_code' => 200, 'execute_time' => 0.014384984970093001, 'available' => 1047, ), 'body' => array ( 'artist_list' => array ( 0 => array ( 'artist' => array ( 'artist_id' => 331046, 'artist_mbid' => 'd024da79-b980-40bb-af2d-d2d56b95b3f3', 'artist_name' => 'Hey! Say! JUMP', 'artist_name_translation_list' => array ( ), 'artist_comment' => '', 'artist_country' => 'JP', 'artist_alias_list' => array ( ), 'artist_rating' => 48, 'primary_genres' => array ( 'music_genre_list' => array ( ), ), 'secondary_genres' => array ( 'music_genre_list' => array ( ), ), 'artist_twitter_url' => '', 'artist_vanity_id' => 'Hey-Say-JUMP', 'artist_share_url' => 'https://www.musixmatch.com/artist/Hey-Say-JUMP', 'artist_credits' => array ( 'artist_list' => array ( ), ), 'restricted' => 0, 'managed' => 0, 'updated_time' => '2013-07-19T08:36:58Z', ), ), 1 => array ( 'artist' => array ( 'artist_id' => 28680882, 'artist_mbid' => '', 'artist_name' => 'Hey Violet', 'artist_name_translation_list' => array ( ), 'artist_comment' => '', 'artist_country' => '', 'artist_alias_list' => array ( 0 => array ( 'artist_alias' => 'ヘイヴァイオレット', ), ), 'artist_rating' => 58, 'primary_genres' => array ( 'music_genre_list' => array ( 0 => array ( 'music_genre' => array ( 'music_genre_id' => 14, 'music_genre_parent_id' => 34, 'music_genre_name' => 'Pop', 'music_genre_name_extended' => 'Pop', 'music_genre_vanity' => 'Pop', ), ), ), ), 'secondary_genres' => array ( 'music_genre_list' => array ( ), ), 'artist_twitter_url' => '', 'artist_credits' => array ( 'artist_list' => array ( ), ), 'restricted' => 0, 'managed' => 0, 'updated_time' => '2015-12-01T22:30:07Z', ), ), 2 => array ( 'artist' => array ( 'artist_id' => 401068, 'artist_mbid' => 'fb45c8d9-4c85-4edf-b41b-af69ad344735', 'artist_name' => 'Hey Monday', 'artist_name_translation_list' => array ( 0 => array ( 'artist_name_translation' => array ( 'language' => 'ZH', 'translation' => '星期一樂團', ), ), 1 => array ( 'artist_name_translation' => array ( 'language' => 'ZH-HANS', 'translation' => '星期一乐团', ), ), ), 'artist_comment' => '', 'artist_country' => 'US', 'artist_alias_list' => array ( 0 => array ( 'artist_alias' => '星期一樂團', ), 1 => array ( 'artist_alias' => '星期一乐团', ), ), 'artist_rating' => 40, 'primary_genres' => array ( 'music_genre_list' => array ( 0 => array ( 'music_genre' => array ( 'music_genre_id' => 20, 'music_genre_parent_id' => 34, 'music_genre_name' => 'Alternative', 'music_genre_name_extended' => 'Alternative', 'music_genre_vanity' => 'Alternative', ), ), ), ), 'secondary_genres' => array ( 'music_genre_list' => array ( ), ), 'artist_twitter_url' => '', 'artist_vanity_id' => 'Hey-Monday', 'artist_share_url' => 'https://www.musixmatch.com/artist/Hey-Monday', 'artist_credits' => array ( 'artist_list' => array ( ), ), 'updated_time' => '2015-12-10T15:24:48Z', ), ), ), ), ), );
		$artistLyrics = $myController->getArtistListFromJSON($responseBody);
		$this->assertEquals(count($artistLyrics), 3);
	}



	/**
	 * @covers App\Http\Controllers\MyController::createSuggestionsFromArtistList()
	**/
	public function testCreateArtistSuggestionsFromValidArtistListOfLengthGreaterThanThree(){
		$myController = new MyController();
		$TestArtistList = array ( 0 => array ( 'artist' => array ( 'artist_id' => 331046, 'artist_mbid' => 'd024da79-b980-40bb-af2d-d2d56b95b3f3', 'artist_name' => 'Hey! Say! JUMP', 'artist_name_translation_list' => array ( ), 'artist_comment' => '', 'artist_country' => 'JP', 'artist_alias_list' => array ( ), 'artist_rating' => 48, 'primary_genres' => array ( 'music_genre_list' => array ( ), ), 'secondary_genres' => array ( 'music_genre_list' => array ( ), ), 'artist_twitter_url' => '', 'artist_vanity_id' => 'Hey-Say-JUMP', 'artist_edit_url' => 'https://www.musixmatch.com/artist/Hey-Say-JUMP?utm_source=application&utm_campaign=api&utm_medium=University+of+Southern+California%2C+CSCI+310', 'artist_share_url' => 'https://www.musixmatch.com/artist/Hey-Say-JUMP', 'artist_credits' => array ( 'artist_list' => array ( ), ), 'restricted' => 0, 'managed' => 0, 'updated_time' => '2013-07-19T08:36:58Z', ), ), 1 => array ( 'artist' => array ( 'artist_id' => 28680882, 'artist_mbid' => '', 'artist_name' => 'Hey Violet', 'artist_name_translation_list' => array ( ), 'artist_comment' => '', 'artist_country' => '', 'artist_alias_list' => array ( 0 => array ( 'artist_alias' => 'ヘイヴァイオレット', ), ), 'artist_rating' => 58, 'primary_genres' => array ( 'music_genre_list' => array ( 0 => array ( 'music_genre' => array ( 'music_genre_id' => 14, 'music_genre_parent_id' => 34, 'music_genre_name' => 'Pop', 'music_genre_name_extended' => 'Pop', 'music_genre_vanity' => 'Pop', ), ), ), ), 'secondary_genres' => array ( 'music_genre_list' => array ( ), ), 'artist_twitter_url' => '', 'artist_vanity_id' => 'HEY-VIOLET', 'artist_edit_url' => 'https://www.musixmatch.com/artist/HEY-VIOLET?utm_source=application&utm_campaign=api&utm_medium=University+of+Southern+California%2C+CSCI+310', 'artist_share_url' => 'https://www.musixmatch.com/artist/HEY-VIOLET', 'artist_credits' => array ( 'artist_list' => array ( ), ), 'restricted' => 0, 'managed' => 0, 'updated_time' => '2015-12-01T22:30:07Z', ), ), 2 => array ( 'artist' => array ( 'artist_id' => 401068, 'artist_mbid' => 'fb45c8d9-4c85-4edf-b41b-af69ad344735', 'artist_name' => 'Hey Monday', 'artist_name_translation_list' => array ( 0 => array ( 'artist_name_translation' => array ( 'language' => 'ZH', 'translation' => '星期一樂團', ), ), 1 => array ( 'artist_name_translation' => array ( 'language' => 'ZH-HANS', 'translation' => '星期一乐团', ), ), ), 'artist_comment' => '', 'artist_country' => 'US', 'artist_alias_list' => array ( 0 => array ( 'artist_alias' => '星期一樂團', ), 1 => array ( 'artist_alias' => '星期一乐团', ), ), 'artist_rating' => 40, 'primary_genres' => array ( 'music_genre_list' => array ( 0 => array ( 'music_genre' => array ( 'music_genre_id' => 20, 'music_genre_parent_id' => 34, 'music_genre_name' => 'Alternative', 'music_genre_name_extended' => 'Alternative', 'music_genre_vanity' => 'Alternative', ), ), ), ), 'secondary_genres' => array ( 'music_genre_list' => array ( ), ), 'artist_twitter_
//url' => '', 'artist_vanity_id' => 'Hey-Monday', 'artist_edit_url' => 'https://www.musixmatch.com/artist/Hey-Monday?utm_source=application&utm_campaign=api&utm_medium=University+of+Southern+California%2C+CSCI+310', 'artist_share_url' => 'https://www.musixmatch.com/artist/Hey-Monday', 'artist_credits' => array ( 'artist_list' => array ( ), ), 'restricted' => 0, 'managed' => 0, 'updated_time' => '2015-12-10T15:24:48Z', ), ), );

		$artistSuggestions = $myController->createSuggestionsFromArtistList($TestArtistList);
		$this->assertEquals(count($TestArtistList), count($artistSuggestions));
	}


	/**
	 * @covers App\Http\Controllers\MyController::createSuggestionsFromArtistList()
	**/
	public function testGetSuggestionsFromArtistListFromInvalidInput(){
		$myController = new MyController();
		$emptyString = "dd"; 
		try{
			$this->expectException($myController->createSuggestionsFromArtistList($emptyString));
		} catch (Exception $e){
			$this->assertEquals(1, 1);
		}
	}


	/**
	 * @covers App\Http\Controllers\MyController::getAllArtistLyrics()
	**/
	public function testGetAllArtistLyricsFromValidTrackList(){
		$myController = new MyController();
		$trackList = array ( 0 => array ( 'track' => array ( 'track_id' => 83087695, 'track_mbid' => '', 'track_isrc' => '', 'track_spotify_id' => '', 'track_soundcloud_id' => '', 'track_xboxmusic_id' => '', 'track_name' => 'This Is Why', 'track_name_translation_list' => array ( ), 'track_rating' => 48, 'track_length' => 0, 'commontrack_id' => 46416850, 'instrumental' => 0, 'explicit' => 0, 'has_lyrics' => 1, 'has_subtitles' => 1, 'has_richsync' => 0, 'num_favourite' => 286, 'lyrics_id' => 11286669, 'subtitle_id' => 13026678, 'album_id' => 20773042, 'album_name' => 'Compilation', 'artist_id' => 28680882, 'artist_mbid' => '', 'artist_name' => 'Hey Violet', 'album_coverart_100x100' => 'http://s.mxmcdn.net/images-storage/albums/nocover.png', 'album_coverart_350x350' => '', 'album_coverart_500x500' => '', 'album_coverart_800x800' => '', 'track_share_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/This-Is-Why', 'track_edit_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/This-Is-Why/edit?utm_source=application&utm_campaign=api&utm_medium=University+of+Southern+California%2C+CSCI+310', 'commontrack_vanity_id' => 'HEY-VIOLET/This-Is-Why', 'restricted' => 0, 'first_release_date' => '', 'updated_time' => '2015-05-02T19:09:33Z', 'primary_genres' => array ( 'music_genre_list' => array ( ), ), 'secondary_genres' => array ( 'music_genre_list' => array ( ), ), ), ), 
1 => array ( 'track' => array ( 'track_id' => 83748948, 'track_mbid' => '', 'track_isrc' => '', 'track_spotify_id' => '', 'track_soundcloud_id' => '', 'track_xboxmusic_id' => '', 'track_name' => 'I Can Feel It', 'track_name_translation_list' => array ( ), 'track_rating' => 52, 'track_length' => 197, 'commontrack_id' => 46669937, 'instrumental' => 0, 'explicit' => 0, 'has_lyrics' => 1, 'has_subtitles' => 1, 'has_richsync' => 0, 'num_favourite' => 606, 'lyrics_id' => 11953341, 'subtitle_id' => 13878454, 'album_id' => 20835578, 'album_name' => 'I Can Feel It', 'artist_id' => 28680882, 'artist_mbid' => '', 'artist_name' => 'Hey Violet', 'album_coverart_100x100' => 'http://s.mxmcdn.net/images-storage/albums/nocover.png', 'album_coverart_350x350' => '', 'album_coverart_500x500' => '', 'album_coverart_800x800' => '', 'track_share_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/I-Can-Feel-It', 'track_edit_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/I-Can-Feel-It/edit?utm_source=application&utm_campaign=api&utm_medium=University+of+Southern+California%2C+CSCI+310', 'commontrack_vanity_id' => 'HEY-VIOLET/I-Can-Feel-It', 'restricted' => 0, 'first_release_date' => '2015-07-17T00:00:00Z', 'updated_time' => '2015-10-14T20:08:21Z', 'primary_genres' => array ( 'music_genre_list' => array ( 0 => array ( 'music_genre' => array ( 'music_genre_id' => 14, 'music_genre_parent_id' => 34, 'music_genre_name' => 'Pop', 'music_genre_name_extended' => 'Pop', 'music_genre_vanity' => 'Pop', ), ), ), ), 'secondary_genres' => array ( 'music_genre_list' => array ( ), ), ), ), 2 => array ( 'track' => array ( 'track_id' => 83589643, 'track_mbid' => '', 'track_isrc' => '', 'track_spotify_id' => '', 'track_soundcloud_id' => '', 'track_xboxmusic_id' => '', 'track_name' => 'I\'m There', 'track_name_translation_list' => array ( ), 'track_rating' => 47, 'track_length' => 0, 'commontrack_id' => 46796253, 'instrumental' => 0, 'explicit' => 0, 'has_lyrics' => 1, 'has_subtitles' => 1, 'has_richsync' => 0, 'num_favourite' => 229, 'lyrics_id' => 11714733, 'subtitle_id' => 10960422, 'album_id' => 20773042, 'album_name' => 'Compilation', 'artist_id' => 28680882, 'artist_mbid' => '', 'artist_name' => 'Hey Violet', 'album_coverart_100x100' => 'http://s.mxmcdn.net/images-storage/albums/nocover.png', 'album_coverart_350x350' => '', 'album_coverart_500x500' => '', 'album_coverart_800x800' => '', 'track_share_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/I-m-There', 'track_edit_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/I-m-There/edit?utm_source=application&utm_campaign=api&utm_medium=University+of+Southern+California%2C+CSCI+310', 'commontrack_vanity_id' => 'HEY-VIOLET/I-m-There', 'restricted' => 0, 'first_release_date' => '', 'updated_time' => '2015-10-17T12:15:27Z', 'primary_genres' => array ( 'music_genre_list' => array ( ), ), 
'secondary_genres' => array ( 'music_genre_list' => array ( ), ), ), ), 3 => array ( 'track' => array ( 'track_id' => 83748949, 'track_mbid' => '', 'track_isrc' => '', 'track_spotify_id' => '', 'track_soundcloud_id' => '', 'track_xboxmusic_id' => '', 'track_name' => 'Smash Into You', 'track_name_translation_list' => array ( ), 'track_rating' => 48, 'track_length' => 181, 'commontrack_id' => 46922999, 'instrumental' => 0, 'explicit' => 0, 'has_lyrics' => 1, 'has_subtitles' => 1, 'has_richsync' => 0, 'num_favourite' => 264, 'lyrics_id' => 11953387, 'subtitle_id' => 12513770, 'album_id' => 20835578, 'album_name' => 'I Can Feel It', 'artist_id' => 28680882, 'artist_mbid' => '', 'artist_name' => 'Hey Violet', 'album_coverart_100x100' => 'http://s.mxmcdn.net/images-storage/albums/nocover.png', 'album_coverart_350x350' => '', 'album_coverart_500x500' => '', 'album_coverart_800x800' => '', 'track_share_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/Smash-Into-You', 'track_edit_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/Smash-Into-You/edit?utm_source=application&utm_campaign=api&utm_medium=University+of+Southern+California%2C+CSCI+310', 
'commontrack_vanity_id' => 'HEY-VIOLET/Smash-Into-You', 'restricted' => 0, 'first_release_date' => '2015-07-17T00:00:00Z', 'updated_time' => '2015-09-18T15:39:44Z', 'primary_genres' => array ( 'music_genre_list' => array ( 0 => array ( 'music_genre' => array ( 'music_genre_id' => 14, 'music_genre_parent_id' => 34, 'music_genre_name' => 'Pop', 'music_genre_name_extended' => 'Pop', 'music_genre_vanity' => 'Pop', ), ), ), ), 'secondary_genres' => array ( 'music_genre_list' => array ( ), ), ), ), 4 => array ( 'track' => array ( 'track_id' => 113908837, 'track_mbid' => '', 'track_isrc' => '', 'track_spotify_id' => '', 'track_soundcloud_id' => '', 'track_xboxmusic_id' => '', 'track_name' => 'Fuqboi', 'track_name_translation_list' => array ( ), 'track_rating' => 52, 'track_length' => 187, 'commontrack_id' => 62745785, 'instrumental' => 0, 'explicit' => 1, 'has_lyrics' => 1, 'has_subtitles' => 1, 'has_richsync' => 0, 'num_favourite' => 235, 'lyrics_id' => 16359345, 'subtitle_id' => 14626088, 'album_id' => 23877495, 'album_name' => 'Brand New Moves', 'artist_id' => 28680882, 'artist_mbid' => '', 'artist_name' => 'Hey Violet', 'album_coverart_100x100' => 'http://s.mxmcdn.net/images-storage/albums/nocover.png', 'album_coverart_350x350' => '', 'album_coverart_500x500' => '', 'album_coverart_800x800' => '', 'track_share_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/Fuqboi', 'track_edit_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/Fuqboi/edit?utm_source=application&utm_campaign=api&utm_medium=University+of+Southern+California%2C+CSCI+310', 'commontrack_vanity_id' => 'HEY-VIOLET/Fuqboi', 'restricted' => 0, 'first_release_date' => '2016-08-16T00:00:00Z', 'updated_time' => '2017-03-04T06:20:44Z', 'primary_genres' => array ( 'music_genre_list' => array ( 0 => array ( 'music_genre' => array ( 'music_genre_id' => 14, 'music_genre_parent_id' => 34, 'music_genre_name' => 'Pop', 'music_genre_name_extended' => 'Pop', 'music_genre_vanity' => 'Pop', ), ), ), ), 'secondary_genres' => array ( 'music_genre_list' => array ( ), ), ), ), ); 

		$artistLyrics = $myController->getAllArtistLyrics($trackList);
		$this->assertEquals(1, 1);
	}


	public function 
} 
?>
