<?php

use PHPUnit\Framework\TestCase;
Use App\Http\Controllers\MyController;

//require __DIR__ . "/../src/MyController.php";


class SongListGenerationTest extends TestCase{


	/**
	 * @covers App\Http\Controllers\MyController::getSongListFromTrackList()
	**/
	public function testSongListGenerationFromTrackList(){
		$myController = new MyController();
		
		$trackList = array ( 0 => array ( 'track' => array ( 'track_id' => 83087695, 'track_mbid' => '', 'track_isrc' => '', 'track_spotify_id' => '', 'track_soundcloud_id' => '', 'track_xboxmusic_id' => '', 'track_name' => 'This Is Why', 'track_name_translation_list' => array ( ), 'track_rating' => 48, 'track_length' => 0, 'commontrack_id' => 46416850, 'instrumental' => 0, 'explicit' => 0, 'has_lyrics' => 1, 'has_subtitles' => 1, 'has_richsync' => 0, 'num_favourite' => 286, 'lyrics_id' => 11286669, 'subtitle_id' => 13026678, 'album_id' => 20773042, 'album_name' => 'Compilation', 'artist_id' => 28680882, 'artist_mbid' => '', 'artist_name' => 'Hey Violet', 'album_coverart_100x100' => 'http://s.mxmcdn.net/images-storage/albums/nocover.png', 'album_coverart_350x350' => '', 'album_coverart_500x500' => '', 'album_coverart_800x800' => '', 'track_share_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/This-Is-Why', 'track_edit_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/This-Is-Why/edit?utm_source=application&utm_campaign=api&utm_medium=University+of+Southern+California%2C+CSCI+310', 'commontrack_vanity_id' => 'HEY-VIOLET/This-Is-Why', 'restricted' => 0, 'first_release_date' => '', 'updated_time' => '2015-05-02T19:09:33Z', 'primary_genres' => array ( 'music_genre_list' => array ( ), ), 'secondary_genres' => array ( 'music_genre_list' => array ( ), ), ), ), 1 => array ( 'track' => array ( 'track_id' => 83748948, 'track_mbid' => '', 'track_isrc' => '', 'track_spotify_id' => '', 'track_soundcloud_id' => '', 'track_xboxmusic_id' => '', 'track_name' => 'I Can Feel It', 'track_name_translation_list' => array ( ), 'track_rating' => 52, 'track_length' => 197, 'commontrack_id' => 46669937, 
'instrumental' => 0, 'explicit' => 0, 'has_lyrics' => 1, 'has_subtitles' => 1, 'has_richsync' => 0, 'num_favourite' => 606, 'lyrics_id' => 11953341, 'subtitle_id' => 13878454, 'album_id' => 20835578, 'album_name' => 'I Can Feel It', 'artist_id' => 28680882, 'artist_mbid' => '', 'artist_name' => 'Hey Violet', 'album_coverart_100x100' => 'http://s.mxmcdn.net/images-storage/albums/nocover.png', 'album_coverart_350x350' => '', 'album_coverart_500x500' => '', 'album_coverart_800x800' => '', 'track_share_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/I-Can-Feel-It', 'track_edit_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/I-Can-Feel-It/edit?utm_source=application&utm_campaign=api&utm_medium=University+of+Southern+California%2C+CSCI+310', 'commontrack_vanity_id' => 'HEY-VIOLET/I-Can-Feel-It', 'restricted' => 0, 'first_release_date' => '2015-07-17T00:00:00Z', 'updated_time' => '2015-10-14T20:08:21Z', 'primary_genres' => array ( 'music_genre_list' => array ( 0 => array ( 'music_genre' => array ( 'music_genre_id' => 14, 'music_genre_parent_id' => 34, 'music_genre_name' => 'Pop', 'music_genre_name_extended' => 'Pop', 'music_genre_vanity' => 'Pop', ), ), ), ), 'secondary_genres' => array ( 'music_genre_list' => array ( ), ), ), ), 2 => array ( 'track' => array ( 'track_id' => 83589643, 'track_mbid' => '', 'track_isrc' => '', 'track_spotify_id' => '', 'track_soundcloud_id' => '', 'track_xboxmusic_id' => '', 'track_name' => 'I\'m There', 'track_name_translation_list' => array ( ), 'track_rating' => 47, 'track_length' => 0, 'commontrack_id' => 46796253, 'instrumental' => 0, 'explicit' => 0, 'has_lyrics' => 1, 'has_subtitles' => 1, 'has_richsync' => 0, 'num_favourite' => 229, 'lyrics_id' => 11714733, 'subtitle_id' => 10960422, 'album_id' => 20773042, 'album_name' => 'Compilation', 'artist_id' => 28680882, 'artist_mbid' => '', 'artist_name' => 'Hey Violet', 'album_coverart_100x100' => 'http://s.mxmcdn.net/images-storage/albums/nocover.png', 'album_coverart_350x350' => '', 'album_coverart_500x500' => '', 'album_coverart_800x800' => '', 'track_share_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/I-m-There', 'track_edit_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/I-m-There/edit?utm_source=application&utm_campaign=api&utm_medium=University+of+Southern+California%2C+CSCI+310', 'commontrack_vanity_id' => 'HEY-VIOLET/I-m-There', 'restricted' => 0, 'first_release_date' => '', 'updated_time' => '2015-10-17T12:15:27Z', 'primary_genres' => array ( 'music_genre_list' => array ( ), ), 'secondary_genres' => array ( 'music_genre_list' => array ( ), ), ), ), 3 => array ( 'track' => array ( 'track_id' => 83748949, 'track_mbid' => '', 'track_isrc' => '', 'track_spotify_id' => '', 
'track_soundcloud_id' => '', 'track_xboxmusic_id' => '', 'track_name' => 'Smash Into You', 'track_name_translation_list' => array ( ), 'track_rating' => 48, 'track_length' => 181, 'commontrack_id' => 46922999, 'instrumental' => 0, 'explicit' => 0, 'has_lyrics' => 1, 'has_subtitles' => 1, 'has_richsync' => 0, 'num_favourite' => 264, 'lyrics_id' => 11953387, 'subtitle_id' => 12513770, 'album_id' => 20835578, 'album_name' => 'I Can Feel It', 'artist_id' => 28680882, 'artist_mbid' => '', 'artist_name' => 'Hey Violet', 'album_coverart_100x100' => 'http://s.mxmcdn.net/images-storage/albums/nocover.png', 'album_coverart_350x350' => '', 'album_coverart_500x500' => '', 'album_coverart_800x800' => '', 'track_share_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/Smash-Into-You', 'track_edit_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/Smash-Into-You/edit?utm_source=application&utm_campaign=api&utm_medium=University+of+Southern+California%2C+CSCI+310', 'commontrack_vanity_id' => 'HEY-VIOLET/Smash-Into-You', 'restricted' => 0, 'first_release_date' => '2015-07-17T00:00:00Z', 'updated_time' => '2015-09-18T15:39:44Z', 'primary_genres' => array ( 'music_genre_list' => array ( 0 => array ( 'music_genre' => array ( 'music_genre_id' => 14, 'music_genre_parent_id' => 34, 'music_genre_name' => 'Pop', 'music_genre_name_extended' => 'Pop', 'music_genre_vanity' => 'Pop', ), ), ), ), 'secondary_genres' => array ( 'music_genre_list' => array ( ), ), ), ), 4 => array ( 'track' => array ( 'track_id' => 113908837, 'track_mbid' => '', 'track_isrc' => '', 'track_spotify_id' => '', 'track_soundcloud_id' => '', 'track_xboxmusic_id' => '', 'track_name' => 'Fuqboi', 'track_name_translation_list' => array ( ), 'track_rating' => 52, 'track_length' => 187, 'commontrack_id' => 62745785, 'instrumental' => 0, 'explicit' => 1, 'has_lyrics' => 1, 'has_subtitles' => 1, 'has_richsync' => 0, 'num_favourite' => 235, 'lyrics_id' => 16359345, 'subtitle_id' => 14626088, 'album_id' => 23877495, 'album_name' => 'Brand New Moves', 'artist_id' => 28680882, 'artist_mbid' => '', 'artist_name' => 'Hey Violet', 'album_coverart_100x100' => 'http://s.mxmcdn.net/images-storage/albums/nocover.png', 'album_coverart_350x350' => '', 'album_coverart_500x500' => '', 'album_coverart_800x800' => '', 'track_share_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/Fuqboi', 'track_edit_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/Fuqboi/edit?utm_source=application&utm_campaign=api&utm_medium=University+of+Southern+California%2C+CSCI+310', 'commontrack_vanity_id' => 'HEY-VIOLET/Fuqboi', 'restricted' => 0, 'first_release_date' => '2016-08-16T00:00:00Z', 'updated_time' => '2017-03-04T06:20:44Z', 'primary_genres' => array ( 'music_genre_list' => array ( 0 => array ( 'music_genre' => array ( 'music_genre_id' => 14, 
'music_genre_parent_id' => 34, 'music_genre_name' => 'Pop', 'music_genre_name_extended' => 'Pop', 'music_genre_vanity' => 'Pop', ), ), ), ), 'secondary_genres' => array ( 'music_genre_list' => array ( ), ), ), ), );
		$artistId = 28680882;
		$word = "know"; 
		$songList = $myController->getSongListFromTrackList($trackList, $artistId, $word);
		$this->assertEquals(count($songList), 5);
	}


	/**
	 * @covers App\Http\Controllers\MyController::parseLyrics()
	**/
	public function testLyricsParsing(){
		$myController = new MyController();
		$originalLyrics = "I've got your number I don´t know how long I can wait (oh oh oh oh oh) (oh oh oh oh oh) To call you over So we can waste the night away (oh oh oh oh oh) (oh oh oh oh oh) When the lights go out We're getting up We go where we go We do what we want Do want we want We'll be the colour in All this black and white Are you feeling what I'm feeling 'Cause it's really feeling right Don't wake me if I'm dreaming I could stay here all night I can feel it I can feel it I can feel it coming true I can feel it I can feel it When I'm looking at you Are you feeling what I'm feeling 'Cause i'm really feeling fine Kicking bottles under bleachers And we're hiding from the light I can feel it I can feel it I can feel it coming true I can feel it I can feel it ... ******* This Lyrics is NOT for Commercial use ******* (1409614316181) ";
		$parsedLyrics = $myController->parseLyrics($originalLyrics);
		$this->assertEquals(strpos($parsedLyrics, "This Lyrics"), false);
	}
} 
?>
