<?php

use PHPUnit\Framework\TestCase;
Use App\Http\Controllers\MyController;

//require __DIR__ . "/../src/MyController.php";


class WordCloudGenerationTest extends TestCase{

	/**
	 * @covers App\Http\Controllers\MyController::getAllArtistLyrics()
	**/
	public function testGetAllArtistLyricsFromValidTrackList(){
		$myController = new MyController();
		$trackList = array ( 0 => array ( 'track' => array ( 'track_id' => 83087695, 'track_mbid' => '', 'track_isrc' => '', 'track_spotify_id' => '', 'track_soundcloud_id' => '', 'track_xboxmusic_id' => '', 'track_name' => 'This Is Why', 'track_name_translation_list' => array ( ), 'track_rating' => 48, 'track_length' => 0, 'commontrack_id' => 46416850, 'instrumental' => 0, 'explicit' => 0, 'has_lyrics' => 1, 'has_subtitles' => 1, 'has_richsync' => 0, 'num_favourite' => 286, 'lyrics_id' => 11286669, 'subtitle_id' => 13026678, 'album_id' => 20773042, 'album_name' => 'Compilation', 'artist_id' => 28680882, 'artist_mbid' => '', 'artist_name' => 'Hey Violet', 'album_coverart_100x100' => 'http://s.mxmcdn.net/images-storage/albums/nocover.png', 'album_coverart_350x350' => '', 'album_coverart_500x500' => '', 'album_coverart_800x800' => '', 'track_share_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/This-Is-Why', 'track_edit_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/This-Is-Why/edit?utm_source=application&utm_campaign=api&utm_medium=University+of+Southern+California%2C+CSCI+310', 'commontrack_vanity_id' => 'HEY-VIOLET/This-Is-Why', 'restricted' => 0, 'first_release_date' => '', 'updated_time' => '2015-05-02T19:09:33Z', 'primary_genres' => array ( 'music_genre_list' => array ( ), ), 'secondary_genres' => array ( 'music_genre_list' => array ( ), ), ), ), 
1 => array ( 'track' => array ( 'track_id' => 83748948, 'track_mbid' => '', 'track_isrc' => '', 'track_spotify_id' => '', 'track_soundcloud_id' => '', 'track_xboxmusic_id' => '', 'track_name' => 'I Can Feel It', 'track_name_translation_list' => array ( ), 'track_rating' => 52, 'track_length' => 197, 'commontrack_id' => 46669937, 'instrumental' => 0, 'explicit' => 0, 'has_lyrics' => 1, 'has_subtitles' => 1, 'has_richsync' => 0, 'num_favourite' => 606, 'lyrics_id' => 11953341, 'subtitle_id' => 13878454, 'album_id' => 20835578, 'album_name' => 'I Can Feel It', 'artist_id' => 28680882, 'artist_mbid' => '', 'artist_name' => 'Hey Violet', 'album_coverart_100x100' => 'http://s.mxmcdn.net/images-storage/albums/nocover.png', 'album_coverart_350x350' => '', 'album_coverart_500x500' => '', 'album_coverart_800x800' => '', 'track_share_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/I-Can-Feel-It', 'track_edit_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/I-Can-Feel-It/edit?utm_source=application&utm_campaign=api&utm_medium=University+of+Southern+California%2C+CSCI+310', 'commontrack_vanity_id' => 'HEY-VIOLET/I-Can-Feel-It', 'restricted' => 0, 'first_release_date' => '2015-07-17T00:00:00Z', 'updated_time' => '2015-10-14T20:08:21Z', 'primary_genres' => array ( 'music_genre_list' => array ( 0 => array ( 'music_genre' => array ( 'music_genre_id' => 14, 'music_genre_parent_id' => 34, 'music_genre_name' => 'Pop', 'music_genre_name_extended' => 'Pop', 'music_genre_vanity' => 'Pop', ), ), ), ), 'secondary_genres' => array ( 'music_genre_list' => array ( ), ), ), ), 2 => array ( 'track' => array ( 'track_id' => 83589643, 'track_mbid' => '', 'track_isrc' => '', 'track_spotify_id' => '', 'track_soundcloud_id' => '', 'track_xboxmusic_id' => '', 'track_name' => 'I\'m There', 'track_name_translation_list' => array ( ), 'track_rating' => 47, 'track_length' => 0, 'commontrack_id' => 46796253, 'instrumental' => 0, 'explicit' => 0, 'has_lyrics' => 1, 'has_subtitles' => 1, 'has_richsync' => 0, 'num_favourite' => 229, 'lyrics_id' => 11714733, 'subtitle_id' => 10960422, 'album_id' => 20773042, 'album_name' => 'Compilation', 'artist_id' => 28680882, 'artist_mbid' => '', 'artist_name' => 'Hey Violet', 'album_coverart_100x100' => 'http://s.mxmcdn.net/images-storage/albums/nocover.png', 'album_coverart_350x350' => '', 'album_coverart_500x500' => '', 'album_coverart_800x800' => '', 'track_share_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/I-m-There', 'track_edit_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/I-m-There/edit?utm_source=application&utm_campaign=api&utm_medium=University+of+Southern+California%2C+CSCI+310', 'commontrack_vanity_id' => 'HEY-VIOLET/I-m-There', 'restricted' => 0, 'first_release_date' => '', 'updated_time' => '2015-10-17T12:15:27Z', 'primary_genres' => array ( 'music_genre_list' => array ( ), ), 
'secondary_genres' => array ( 'music_genre_list' => array ( ), ), ), ), 3 => array ( 'track' => array ( 'track_id' => 83748949, 'track_mbid' => '', 'track_isrc' => '', 'track_spotify_id' => '', 'track_soundcloud_id' => '', 'track_xboxmusic_id' => '', 'track_name' => 'Smash Into You', 'track_name_translation_list' => array ( ), 'track_rating' => 48, 'track_length' => 181, 'commontrack_id' => 46922999, 'instrumental' => 0, 'explicit' => 0, 'has_lyrics' => 1, 'has_subtitles' => 1, 'has_richsync' => 0, 'num_favourite' => 264, 'lyrics_id' => 11953387, 'subtitle_id' => 12513770, 'album_id' => 20835578, 'album_name' => 'I Can Feel It', 'artist_id' => 28680882, 'artist_mbid' => '', 'artist_name' => 'Hey Violet', 'album_coverart_100x100' => 'http://s.mxmcdn.net/images-storage/albums/nocover.png', 'album_coverart_350x350' => '', 'album_coverart_500x500' => '', 'album_coverart_800x800' => '', 'track_share_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/Smash-Into-You', 'track_edit_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/Smash-Into-You/edit?utm_source=application&utm_campaign=api&utm_medium=University+of+Southern+California%2C+CSCI+310', 
'commontrack_vanity_id' => 'HEY-VIOLET/Smash-Into-You', 'restricted' => 0, 'first_release_date' => '2015-07-17T00:00:00Z', 'updated_time' => '2015-09-18T15:39:44Z', 'primary_genres' => array ( 'music_genre_list' => array ( 0 => array ( 'music_genre' => array ( 'music_genre_id' => 14, 'music_genre_parent_id' => 34, 'music_genre_name' => 'Pop', 'music_genre_name_extended' => 'Pop', 'music_genre_vanity' => 'Pop', ), ), ), ), 'secondary_genres' => array ( 'music_genre_list' => array ( ), ), ), ), 4 => array ( 'track' => array ( 'track_id' => 113908837, 'track_mbid' => '', 'track_isrc' => '', 'track_spotify_id' => '', 'track_soundcloud_id' => '', 'track_xboxmusic_id' => '', 'track_name' => 'Fuqboi', 'track_name_translation_list' => array ( ), 'track_rating' => 52, 'track_length' => 187, 'commontrack_id' => 62745785, 'instrumental' => 0, 'explicit' => 1, 'has_lyrics' => 1, 'has_subtitles' => 1, 'has_richsync' => 0, 'num_favourite' => 235, 'lyrics_id' => 16359345, 'subtitle_id' => 14626088, 'album_id' => 23877495, 'album_name' => 'Brand New Moves', 'artist_id' => 28680882, 'artist_mbid' => '', 'artist_name' => 'Hey Violet', 'album_coverart_100x100' => 'http://s.mxmcdn.net/images-storage/albums/nocover.png', 'album_coverart_350x350' => '', 'album_coverart_500x500' => '', 'album_coverart_800x800' => '', 'track_share_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/Fuqboi', 'track_edit_url' => 'https://www.musixmatch.com/lyrics/HEY-VIOLET/Fuqboi/edit?utm_source=application&utm_campaign=api&utm_medium=University+of+Southern+California%2C+CSCI+310', 'commontrack_vanity_id' => 'HEY-VIOLET/Fuqboi', 'restricted' => 0, 'first_release_date' => '2016-08-16T00:00:00Z', 'updated_time' => '2017-03-04T06:20:44Z', 'primary_genres' => array ( 'music_genre_list' => array ( 0 => array ( 'music_genre' => array ( 'music_genre_id' => 14, 'music_genre_parent_id' => 34, 'music_genre_name' => 'Pop', 'music_genre_name_extended' => 'Pop', 'music_genre_vanity' => 'Pop', ), ), ), ), 'secondary_genres' => array ( 'music_genre_list' => array ( ), ), ), ), ); 

		$artistLyrics = $myController->getAllArtistLyrics($trackList);
		$this->assertEquals(1, 1);
	}


	/**
	 * @covers App\Http\Controllers\MyController::createWordListFromLyrics()
	**/
	public function testCreateWordListFromLyricsList(){
		$myController = new MyController();
		$allLyricsString = "you got attention then stomped out you're there then you're gone what's all about? came strong then backed off when did nerve call love you're part past now making history don't act surprised now don't say didn't see coming if you're wondering why leaving stop second count reasons; don't listen don't care don't try that's reason why there's no way for stop bleeding don't i've got reasons; don't listen don't care don't try that's reason why got affection then threw out i've got your number don´t know long can wait oh oh oh oh oh oh oh oh oh oh call over can waste night away oh oh oh oh oh oh oh oh oh oh when lights go out we're getting up go where go what want want want we'll colour all black white feeling what feeling 'cause really feeling right don't wake if dreaming could stay here all night can feel can feel can feel coming true can feel can feel when looking you feeling what feeling 'cause really feeling fine kicking bottles under bleachers we're hiding from light can feel can feel can feel coming true can feel can feel i must say never like i'll break down don't miss point got something i've been hoping looking for real long time not gonna waste between heart mind much lost little time know word can spoken then world can opened up faith reborn will never waste if don't wanna alone just want heart call own just have say word there there 'cause no one wants alone feelings like need home just have say word there there stand still don't give sigh i'd love think yours you're mine i'll wherever needed wanted i don't want sweet without line don't want without mine wanna feel yeah just wanna feel know gotta cut just like knife know want hot cold as ice make belive 'cause gotta belive 'cause just wild thing give real thing baby wind up watch go don't need no parachute you're not ever gonna catch fall slow down 'cause just wanna hit ground smash into when jump wanna recklessly when take aim yeah you're gonna know name when smash into there's guy school he looks pretty good always asking when can kick well friends think wrong he's not what want cause he's constantly begging for pictures when there's cute things he'd say bet he stole 'em from drake did mention he wears his mom's earrings know he's tall he's fit won't fall for don't want his hands his lips coming near cause he's fuqboi they're all same like stain your heart's reputation yeah you're fuqboi i've been through before i'd rather cut out tongue ";
		$wordList = $myController->createWordListFromLyrics($allLyricsString);
		$this->assertEquals(count($wordList) <= 250, true);
	}

	/**
	 * @covers App\Http\Controllers\MyController::createWordCloudString()
	**/
	public function testCreationOfHTMLWordCloudStringFromWordFrequencyList(){
		$myController = new MyController();
		$wordList = array ( 'oh' => 20, 'don\'t' => 17, 'can' => 15, 'feel' => 12, 'want' => 9, 'when' => 8, 'you\'re' => 8, 'just' => 7, 'know' => 6, 'feeling' => 6, '\'cause' => 6, 'wanna' => 5, 'got' => 5, 'say' => 5, 'he\'s' => 5, 'then' => 5, 'there' => 5, 'coming' => 4, 'what' => 4, 'i\'ve' => 4, 'for' => 4, 'out' => 4, 'go' => 4, 'all' => 4, 'like' => 4, 'why' => 3, 'waste' => 3, 'word' => 3, 'gonna' => 3, 'there\'s' => 3, 'no' => 3, 'not' => 3, 'if' => 3, 'up' => 3, 'he' => 3, 'yeah' => 3, 'call' => 3, 'his' => 3, 'cause' => 2, 'into' => 2, 'smash' => 2, 'i' => 2, 'really' => 2, 'thing' => 2, 'belive' => 2, 'true' => 2, 'looking' => 2, 'fuqboi' => 2, 'from' => 2, 'fall' => 2, 'have' => 2, 'cut' => 2, 'alone' => 2, 'gotta' => 2, 'without' => 2, 'i\'ll' => 2, 'down' => 2, 'been' => 2, 'real' => 2, 'time' => 2, 'mine' => 2, 'think' => 2, 'heart' => 2, 'i\'d' => 2, 'give' => 2, 'need' => 2, 'never' => 2, 'you' => 2, 'we\'re' => 2, 'your' => 2, 'now' => 2, 'did' => 2, 'stop' => 2, 'reasons;' => 2, 'listen' => 2, 'love' => 2, 'try' => 2, 'that\'s' => 2, 'reason' => 2, 'care' => 2, 'long' => 2, 'night' => 2, 'take' => 1, 'ground' => 1, 'strong' => 1, 'came' => 1, 'jump' => 1, 'recklessly' => 1, 'name' => 1, 'aim' => 1, 'slow' => 1, 'guy' => 1, 'school' => 1, 'about?' => 1, 'through' => 1, 'looks' => 1, 'hit' => 1, 'backed' => 1, 'good' => 1, 'rather' => 1, 'knife' => 1, 'hot' => 1, 'cold' => 1, 'as' => 1, 'ice' => 1, 'make' => 1, 'before' => 1, 'catch' => 1, 'wild' => 1, 'off' => 1, 'baby' => 1, 'wind' => 1, 'watch' => 1, 'parachute' => 1, 'ever' => 1, 'pretty' => 1, 'always' => 1, 'near' => 1, 'attention' => 1, 'stole' => 1, '\'em' => 1, 'drake' => 1, 'mention' => 1, 'wears' => 1, 'stomped' => 1, 'mom\'s' => 1, 'he\'d' => 1, 'earrings' => 1, 'tall' => 1, 'fit' => 1, 'won\'t' => 1, 'hands' => 1, 'lips' => 1, 'bet' => 1, 'things' => 1, 'asking' => 1, 'wrong' => 1, 'kick' => 1, 'well' => 1, 'reputation' => 1, 'heart\'s' => 1, 'friends' => 1, 'stain' => 1, 'what\'s' => 1, 'cute' => 1, 'gone' => 1, 'same' => 1, 'constantly' => 1, 'they\'re' => 1, 'begging' => 1, 'pictures' => 1, 'nerve' => 1, 'needed' => 1, 'part' => 1, 'light' => 1, 'kicking' => 1, 'bottles' => 1, 'under' => 1, 'bleachers' => 1, 'hiding' => 1, 'threw' => 1, 'affection' => 1, 'number' => 1, 'must' => 1, 'bleeding' => 1, 'way' => 1, 'break' => 1, 'miss' => 1, 'point' => 1, 'fine' => 1, 'don´t' => 1, 'hoping' => 1, 'white' => 1, 'lights' => 1, 'where' => 1, 'away' => 1, 'we\'ll' => 1, 'colour' => 1, 'black' => 1, 'over' => 1, 'here' => 1, 'wait' => 1, 'right' => 1, 'wake' => 1, 'dreaming' => 1, 'could' => 1, 'stay' => 1, 'something' => 1, 'count' => 1, 'line' => 1, 'history' => 1, 'surprised' => 1, 'home' => 1, 'stand' => 1, 'still' => 1, 'act' => 1, 'sigh' => 1, 'making' => 1, 'wants' => 1, 'yours' => 1, 'wherever' => 1, 'getting' => 1, 'wanted' => 1, 'sweet' => 1, 'past' => 1, 'feelings' => 1, 'one' => 1, 'between' => 1, 'world' => 1, 
'second' => 1, 'mind' => 1, 'much' => 1, 'lost' => 1, 'little' => 1, 'spoken' => 1, 'opened' => 1, 'didn\'t' => 1, 'faith' => 1, 'reborn' => 1, 'will' => 1, 'leaving' => 1, 'wondering' => 1, 'see' => 1, 'own' => 1, 'tongue' => 1, );
		$artistId = 28680882;
		$wordCloudString = $myController->createWordCloudString($wordList, $artistId);

		$this->assertEquals(count($wordCloudString), 1);
	}
} 
?>
